AllCops:
  NewCops: enable

LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/**/*
